apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dosfinal.fullname" . }}-secrets
  labels:
    {{- include "dosfinal.labels" . | nindent 4 }}
type: Opaque
data:
  connection-string: {{ .Values.app.connectionString | b64enc | quote }}
  sa-password: {{ .Values.sqlserver.password | b64enc | quote }}
